spring:
  profiles:
    active: dev
  datasource:
    #url: jdbc:h2:file:./.h2/test;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
  h2:
    console: 
      enabled: true
      path: /h2-console

logging:
  config: classpath:logback.xml

management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
