spring:
  profiles:
    active: pro
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
  health:
    defaults:
      enabled: false
